#include "LilyPond.h"
#include <format>
#include "fm/fm_constants.h"
#include "fe/fe_app_constants.h"

std::string fm::lp::gen_tagline(void) {
	return std::format("generated by {} {} ({})",
		fe::c::APP_NAME, fe::c::APP_VERSION, fe::c::APP_URL);
}

std::string fm::lp::header(const std::string& p_title, const fm::Fraction& p_tempo) {
	std::string result{
		std::format("\\version \"2.24.0\"\n\n\\header {{\n  title = \"{}\"\n  tagline = \"{}\"\n}}\n\n\\score {{\n\n<<\n", p_title, gen_tagline())
	};

	return result;
}

std::string fm::lp::footer(void) {
	std::string result{ ">>\n\\layout { }\n\\midi { }\n}\n" };
	return result;
}

std::string fm::lp::emit_octave(int p_octave) {
	constexpr int DEFAULT_OCTAVE{ 3 };
	std::string result;

	if (p_octave < DEFAULT_OCTAVE)
		for (int i{ DEFAULT_OCTAVE }; i > p_octave; --i)
			result.push_back(',');
	else if (p_octave > DEFAULT_OCTAVE)
		for (int i{ DEFAULT_OCTAVE }; i < p_octave; ++i)
			result.push_back('\'');

	return result;
}

std::string fm::lp::emit_note(int p_pitch, int p_octave,
	const std::string& p_length) {

	static const std::vector<std::string> LP_NOTE_NAMES{
		"c", "cis", "d", "dis", "e", "f",
		"fis", "g", "gis", "a", "ais", "b"
	};

	int l_pitch{ p_pitch };
	int l_octave{ p_octave };

	while (l_pitch < 0) {
		l_pitch += 12;
		--l_octave;
	}

	while (l_pitch >= 12) {
		l_pitch -= 12;
		++l_octave;
	}

	std::string result{ std::format("{}{}{}", LP_NOTE_NAMES[l_pitch],
		emit_octave(l_octave), p_length) };

	return result;
}

std::string fm::lp::emit_percussion(int p_perc_no,
	const std::string& p_length) {
	static const std::vector<std::string> LP_PERC_NAMES{
	"cb", "bd", "sn", "hho", "cb", "hhc", "hhc", "cb"
	};
	return std::format("{}{}", LP_PERC_NAMES.at(p_perc_no), p_length);
}

std::string fm::lp::emit_rest(const std::string& p_length) {
	std::string result{ std::format("r{}", p_length) };
	return result;
}

// TODO: Add more state here, pitch effect and such?
std::string fm::lp::emit_midi_instrument(int p_duty_cycle) {
	static const std::vector<std::string> LP_INSTR_NAMES{
	"lead 1 (square)", "lead 5 (charang)", "lead 2 (sawtooth)", "lead 5 (charang)"
	};

	std::string result{ std::format("\n\\set Staff.midiInstrument = \"{}\"\n",
		LP_INSTR_NAMES.at(p_duty_cycle)) };
	return result;
}
